### ISSUE TITLE
ImportError: cannot import name 'KeyedVectors'

### ISSUE THREAD

**Issue by gustavkkk** [huyingxi/Synonyms#27]
I used 'pip install -U synonyms' to install successfully.
But when i import the library, it doesn't work'. How can i solve this?
Thanks in advance.
#####################################
import synonyms
Traceback (most recent call last):

  File "<ipython-input-36-e6c3357df047>", line 1, in <module>
    import synonyms

  File "C:\Anaconda3\lib\site-packages\synonyms\__init__.py", line 47, in <module>
    from word2vec import KeyedVectors

ImportError: cannot import name 'KeyedVectors'
#######################################
# environment
windows8, python3.5.2, anaconda

**Comment by Samurais** [comment]
word2vec is a package in Synonyms.

![image](https://user-images.githubusercontent.com/3538629/35080188-ff3ab6ec-fc46-11e7-849d-ab0ee181b2bf.png)

I think the reason is you have another package named "word2vec" in PYTHONPATH.
To verify my assumption
```
python
import word2vec 
word2vec.__file__
```

Check out the path, make sure it is the one inside synonyms.

**Comment by gustavkkk** [comment]
Thank you very much.
